# This is a basic workflow to help you get started with Actions
name: Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Select the environment'
        required: true
        default: 'dev'
        options:
          - dev
          - prd

jobs:
  common:
    runs-on: ubuntu-latest
    steps:
      - name: Common Step
        run: echo "This is a common step for both environments"

  dev:
    needs: common
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'dev' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Say Hello
        run: echo "Hello from the dev environment!"

  prd:
    needs: [common]
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'prd' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Say Hello
        run: echo "Hello from the prd environment!"
